
[build]
 
  base = "client/"

  
  publish = "client/"

  # Default build command.
  command = "CI= npm run build"

[[plugins]]
  
  package = "@netlify/plugin-lighthouse"


[context.production]
  publish = "output/"
  command = "make publish"
  environment = { ACCESS_TOKEN = "super secret", NODE_VERSION = "14.15.3" }


[context.deploy-preview]
  publish = "dist/"


  ACCESS_TOKEN = "not so secret"


[context.branch-deploy]
  command = "echo branch"
[context.branch-deploy.environment]
  NODE_ENV = "development"


[context.staging] 
  command = "echo 'staging'"
  base = "staging"


[context."feat/branch"]
  command = "echo 'special branch'"
  base = "branch"


[[redirects]]
  from = "/*"
  to = "/blog/:splat"

# A redirect rule with many of the supported properties
[[redirects]]
  from = "/old-path"
  to = "/new-path"

  
  status = 302

  
  force = true

  
  query = {id = ":id"}

  
  conditions = {Language = ["en"], Country = ["US"]}

  
  signed = "API_SIGNATURE_TOKEN"

  
    X-From = "Netlify"
    X-Api-Key = "some-api-key-string"


[[redirects]]
  from = "/gated-path"
  status = 200
  conditions = {Role = ["admin"]}
  force = true


[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  
  for = "/*"

  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    Content-Security-Policy = "frame-ancestors https://www.facebook.com"

    # Multi-value headers are expressed with multi-line strings.
	cache-control = '''
	max-age=0,
	no-cache,
	no-store,
	must-revalidate'''

    # Basic-Auth allows you to password protect your whole site.
    # This feature may not be available on all plans.
    Basic-Auth = "someuser:somepassword anotheruser:anotherpassword"

[functions]
  # Directory with serverless functions, including background functions,
  # to deploy. This is relative to the base directory if one has been set, 
  # or the root directory if a base hasn’t been set.
  directory = "functions/"

# An Edge Handler declaration
[[edge_handlers]]
  path = "/*"
  handler = "filterRequests"
  